import { Footer, Navbar } from "@/components";
import { Poppins } from "next/font/google";
import Head from "next/head";

export interface LayoutRootProps {
  children: React.ReactNode;
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: "normal",
  display: "swap",
});

export default function LayoutRoot(props: LayoutRootProps) {
  const { children } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </main>
    </>
  );
}
